// data/countries.js
// Liste complète des pays du monde avec code ISO alpha-2, noms acceptés (fr), et continent

const COUNTRIES = [
  // ========================
  // EUROPE (45)
  // ========================
  { code: "fr", names: ["france"], c: "europe" },
  { code: "de", names: ["allemagne"], c: "europe" },
  { code: "it", names: ["italie"], c: "europe" },
  { code: "es", names: ["espagne"], c: "europe" },
  { code: "pt", names: ["portugal"], c: "europe" },
  { code: "gb", names: ["royaume-uni", "royaume uni", "angleterre"], c: "europe" },
  { code: "se", names: ["suede"], c: "europe" },
  { code: "no", names: ["norvege"], c: "europe" },
  { code: "fi", names: ["finlande"], c: "europe" },
  { code: "dk", names: ["danemark"], c: "europe" },
  { code: "pl", names: ["pologne"], c: "europe" },
  { code: "nl", names: ["pays-bas", "pays bas", "hollande"], c: "europe" },
  { code: "be", names: ["belgique"], c: "europe" },
  { code: "ch", names: ["suisse"], c: "europe" },
  { code: "at", names: ["autriche"], c: "europe" },
  { code: "gr", names: ["grece"], c: "europe" },
  { code: "ie", names: ["irlande"], c: "europe" },
  { code: "ua", names: ["ukraine"], c: "europe" },
  { code: "cz", names: ["republique tcheque", "tchequie"], c: "europe" },
  { code: "ro", names: ["roumanie"], c: "europe" },
  { code: "hu", names: ["hongrie"], c: "europe" },
  { code: "hr", names: ["croatie"], c: "europe" },
  { code: "rs", names: ["serbie"], c: "europe" },
  { code: "bg", names: ["bulgarie"], c: "europe" },
  { code: "is", names: ["islande"], c: "europe" },
  { code: "lu", names: ["luxembourg"], c: "europe" },
  { code: "mt", names: ["malte"], c: "europe" },
  { code: "cy", names: ["chypre"], c: "europe" },
  { code: "lv", names: ["lettonie"], c: "europe" },
  { code: "lt", names: ["lituanie"], c: "europe" },
  { code: "ee", names: ["estonie"], c: "europe" },
  { code: "sk", names: ["slovaquie"], c: "europe" },
  { code: "si", names: ["slovenie"], c: "europe" },
  { code: "al", names: ["albanie"], c: "europe" },
  { code: "mk", names: ["macedoine", "macedoine du nord"], c: "europe" },
  { code: "ba", names: ["bosnie", "bosnie-herzegovine", "bosnie herzegovine"], c: "europe" },
  { code: "me", names: ["montenegro"], c: "europe" },
  { code: "md", names: ["moldavie"], c: "europe" },
  { code: "by", names: ["bielorussie", "belarus"], c: "europe" },
  { code: "ad", names: ["andorre"], c: "europe" },
  { code: "mc", names: ["monaco"], c: "europe" },
  { code: "li", names: ["liechtenstein"], c: "europe" },
  { code: "sm", names: ["saint-marin", "saint marin"], c: "europe" },
  { code: "va", names: ["vatican"], c: "europe" },
  { code: "xk", names: ["kosovo"], c: "europe" },

  // ========================
  // ASIE (49)
  // ========================
  { code: "jp", names: ["japon"], c: "asie" },
  { code: "cn", names: ["chine"], c: "asie" },
  { code: "kr", names: ["coree du sud", "coree"], c: "asie" },
  { code: "kp", names: ["coree du nord"], c: "asie" },
  { code: "in", names: ["inde"], c: "asie" },
  { code: "ru", names: ["russie"], c: "asie" },
  { code: "tr", names: ["turquie", "turkiye"], c: "asie" },
  { code: "th", names: ["thailande"], c: "asie" },
  { code: "vn", names: ["vietnam", "viet nam"], c: "asie" },
  { code: "id", names: ["indonesie"], c: "asie" },
  { code: "ph", names: ["philippines"], c: "asie" },
  { code: "my", names: ["malaisie"], c: "asie" },
  { code: "sa", names: ["arabie saoudite"], c: "asie" },
  { code: "ae", names: ["emirats arabes unis", "emirats"], c: "asie" },
  { code: "il", names: ["israel"], c: "asie" },
  { code: "pk", names: ["pakistan"], c: "asie" },
  { code: "bd", names: ["bangladesh"], c: "asie" },
  { code: "sg", names: ["singapour"], c: "asie" },
  { code: "ge", names: ["georgie"], c: "asie" },
  { code: "am", names: ["armenie"], c: "asie" },
  { code: "az", names: ["azerbaidjan"], c: "asie" },
  { code: "kz", names: ["kazakhstan"], c: "asie" },
  { code: "uz", names: ["ouzbekistan"], c: "asie" },
  { code: "mn", names: ["mongolie"], c: "asie" },
  { code: "np", names: ["nepal"], c: "asie" },
  { code: "lk", names: ["sri lanka"], c: "asie" },
  { code: "mm", names: ["birmanie", "myanmar"], c: "asie" },
  { code: "kh", names: ["cambodge"], c: "asie" },
  { code: "la", names: ["laos"], c: "asie" },
  { code: "iq", names: ["irak"], c: "asie" },
  { code: "ir", names: ["iran"], c: "asie" },
  { code: "jo", names: ["jordanie"], c: "asie" },
  { code: "lb", names: ["liban"], c: "asie" },
  { code: "sy", names: ["syrie"], c: "asie" },
  { code: "af", names: ["afghanistan"], c: "asie" },
  { code: "bh", names: ["bahrein"], c: "asie" },
  { code: "bt", names: ["bhoutan"], c: "asie" },
  { code: "bn", names: ["brunei"], c: "asie" },
  { code: "tl", names: ["timor oriental", "timor-oriental", "timor"], c: "asie" },
  { code: "kg", names: ["kirghizistan"], c: "asie" },
  { code: "kw", names: ["koweit"], c: "asie" },
  { code: "mv", names: ["maldives"], c: "asie" },
  { code: "om", names: ["oman"], c: "asie" },
  { code: "ps", names: ["palestine"], c: "asie" },
  { code: "qa", names: ["qatar"], c: "asie" },
  { code: "tj", names: ["tadjikistan"], c: "asie" },
  { code: "tw", names: ["taiwan"], c: "asie" },
  { code: "tm", names: ["turkmenistan"], c: "asie" },
  { code: "ye", names: ["yemen"], c: "asie" },

  // ========================
  // AFRIQUE (54)
  // ========================
  { code: "eg", names: ["egypte"], c: "afrique" },
  { code: "za", names: ["afrique du sud"], c: "afrique" },
  { code: "ng", names: ["nigeria"], c: "afrique" },
  { code: "ke", names: ["kenya"], c: "afrique" },
  { code: "ma", names: ["maroc"], c: "afrique" },
  { code: "dz", names: ["algerie"], c: "afrique" },
  { code: "tn", names: ["tunisie"], c: "afrique" },
  { code: "et", names: ["ethiopie"], c: "afrique" },
  { code: "gh", names: ["ghana"], c: "afrique" },
  { code: "sn", names: ["senegal"], c: "afrique" },
  { code: "ci", names: ["cote d'ivoire", "cote divoire", "côte d'ivoire"], c: "afrique" },
  { code: "cm", names: ["cameroun"], c: "afrique" },
  { code: "ly", names: ["libye"], c: "afrique" },
  { code: "sd", names: ["soudan"], c: "afrique" },
  { code: "ss", names: ["soudan du sud"], c: "afrique" },
  { code: "tz", names: ["tanzanie"], c: "afrique" },
  { code: "ug", names: ["ouganda"], c: "afrique" },
  { code: "mz", names: ["mozambique"], c: "afrique" },
  { code: "mg", names: ["madagascar"], c: "afrique" },
  { code: "cd", names: ["congo", "rdc", "republique democratique du congo"], c: "afrique" },
  { code: "cg", names: ["congo-brazzaville", "republique du congo"], c: "afrique" },
  { code: "ao", names: ["angola"], c: "afrique" },
  { code: "zm", names: ["zambie"], c: "afrique" },
  { code: "zw", names: ["zimbabwe"], c: "afrique" },
  { code: "bw", names: ["botswana"], c: "afrique" },
  { code: "na", names: ["namibie"], c: "afrique" },
  { code: "ml", names: ["mali"], c: "afrique" },
  { code: "bf", names: ["burkina faso", "burkina"], c: "afrique" },
  { code: "ne", names: ["niger"], c: "afrique" },
  { code: "td", names: ["tchad"], c: "afrique" },
  { code: "tg", names: ["togo"], c: "afrique" },
  { code: "bj", names: ["benin"], c: "afrique" },
  { code: "gn", names: ["guinee"], c: "afrique" },
  { code: "ga", names: ["gabon"], c: "afrique" },
  { code: "mr", names: ["mauritanie"], c: "afrique" },
  { code: "rw", names: ["rwanda"], c: "afrique" },
  { code: "bi", names: ["burundi"], c: "afrique" },
  { code: "so", names: ["somalie"], c: "afrique" },
  { code: "er", names: ["erythree"], c: "afrique" },
  { code: "dj", names: ["djibouti"], c: "afrique" },
  { code: "cf", names: ["republique centrafricaine", "centrafrique"], c: "afrique" },
  { code: "cv", names: ["cap-vert", "cap vert"], c: "afrique" },
  { code: "km", names: ["comores"], c: "afrique" },
  { code: "gq", names: ["guinee equatoriale"], c: "afrique" },
  { code: "gw", names: ["guinee-bissau", "guinee bissau"], c: "afrique" },
  { code: "ls", names: ["lesotho"], c: "afrique" },
  { code: "lr", names: ["liberia"], c: "afrique" },
  { code: "mw", names: ["malawi"], c: "afrique" },
  { code: "mu", names: ["ile maurice", "maurice"], c: "afrique" },
  { code: "sz", names: ["eswatini", "swaziland"], c: "afrique" },
  { code: "gm", names: ["gambie"], c: "afrique" },
  { code: "sc", names: ["seychelles"], c: "afrique" },
  { code: "sl", names: ["sierra leone"], c: "afrique" },
  { code: "st", names: ["sao tome-et-principe", "sao tome"], c: "afrique" },

  // ========================
  // AMÉRIQUE DU NORD & CENTRALE (23)
  // ========================
  { code: "us", names: ["etats-unis", "etats unis", "usa"], c: "amerique_nord" },
  { code: "ca", names: ["canada"], c: "amerique_nord" },
  { code: "mx", names: ["mexique"], c: "amerique_nord" },
  { code: "cu", names: ["cuba"], c: "amerique_nord" },
  { code: "cr", names: ["costa rica"], c: "amerique_nord" },
  { code: "pa", names: ["panama"], c: "amerique_nord" },
  { code: "jm", names: ["jamaique"], c: "amerique_nord" },
  { code: "ht", names: ["haiti"], c: "amerique_nord" },
  { code: "do", names: ["republique dominicaine", "dominicaine"], c: "amerique_nord" },
  { code: "gt", names: ["guatemala"], c: "amerique_nord" },
  { code: "hn", names: ["honduras"], c: "amerique_nord" },
  { code: "sv", names: ["salvador", "el salvador"], c: "amerique_nord" },
  { code: "ni", names: ["nicaragua"], c: "amerique_nord" },
  { code: "tt", names: ["trinite-et-tobago", "trinite et tobago", "trinidad"], c: "amerique_nord" },
  { code: "bz", names: ["belize"], c: "amerique_nord" },
  { code: "bs", names: ["bahamas"], c: "amerique_nord" },
  { code: "bb", names: ["barbade"], c: "amerique_nord" },
  { code: "ag", names: ["antigua-et-barbuda", "antigua et barbuda", "antigua"], c: "amerique_nord" },
  { code: "dm", names: ["dominique"], c: "amerique_nord" },
  { code: "gd", names: ["grenade"], c: "amerique_nord" },
  { code: "kn", names: ["saint-kitts-et-nevis", "saint kitts"], c: "amerique_nord" },
  { code: "lc", names: ["sainte-lucie", "sainte lucie"], c: "amerique_nord" },
  { code: "vc", names: ["saint-vincent-et-les-grenadines", "saint vincent"], c: "amerique_nord" },

  // ========================
  // AMÉRIQUE DU SUD (12)
  // ========================
  { code: "br", names: ["bresil"], c: "amerique_sud" },
  { code: "ar", names: ["argentine"], c: "amerique_sud" },
  { code: "co", names: ["colombie"], c: "amerique_sud" },
  { code: "cl", names: ["chili"], c: "amerique_sud" },
  { code: "pe", names: ["perou"], c: "amerique_sud" },
  { code: "uy", names: ["uruguay"], c: "amerique_sud" },
  { code: "py", names: ["paraguay"], c: "amerique_sud" },
  { code: "ec", names: ["equateur"], c: "amerique_sud" },
  { code: "ve", names: ["venezuela"], c: "amerique_sud" },
  { code: "bo", names: ["bolivie"], c: "amerique_sud" },
  { code: "gy", names: ["guyana"], c: "amerique_sud" },
  { code: "sr", names: ["suriname"], c: "amerique_sud" },

  // ========================
  // OCÉANIE (14)
  // ========================
  { code: "au", names: ["australie"], c: "oceanie" },
  { code: "nz", names: ["nouvelle-zelande", "nouvelle zelande"], c: "oceanie" },
  { code: "fj", names: ["fidji"], c: "oceanie" },
  { code: "pg", names: ["papouasie-nouvelle-guinee", "papouasie nouvelle guinee", "papouasie"], c: "oceanie" },
  { code: "ws", names: ["samoa"], c: "oceanie" },
  { code: "to", names: ["tonga"], c: "oceanie" },
  { code: "vu", names: ["vanuatu"], c: "oceanie" },
  { code: "ki", names: ["kiribati"], c: "oceanie" },
  { code: "fm", names: ["micronesie"], c: "oceanie" },
  { code: "mh", names: ["marshall", "iles marshall"], c: "oceanie" },
  { code: "nr", names: ["nauru"], c: "oceanie" },
  { code: "pw", names: ["palaos", "palau"], c: "oceanie" },
  { code: "sb", names: ["salomon", "iles salomon"], c: "oceanie" },
  { code: "tv", names: ["tuvalu"], c: "oceanie" },
];

const CATEGORIES = [
  { id: "all",           name: "Tous les pays",               icon: "🌍", filter: () => COUNTRIES },
  { id: "europe",        name: "Europe",                      icon: "🇪🇺", filter: () => COUNTRIES.filter(c => c.c === "europe") },
  { id: "asie",          name: "Asie",                        icon: "🌏", filter: () => COUNTRIES.filter(c => c.c === "asie") },
  { id: "afrique",       name: "Afrique",                     icon: "🌍", filter: () => COUNTRIES.filter(c => c.c === "afrique") },
  { id: "amerique_nord", name: "Amérique du Nord & Centrale", icon: "🌎", filter: () => COUNTRIES.filter(c => c.c === "amerique_nord") },
  { id: "amerique_sud",  name: "Amérique du Sud",             icon: "🌎", filter: () => COUNTRIES.filter(c => c.c === "amerique_sud") },
  { id: "oceanie",       name: "Océanie",                     icon: "🏝️", filter: () => COUNTRIES.filter(c => c.c === "oceanie") },
];
